version: '2'

services:
  postgresql:
    image: postgres:9.6
    container_name: postgresql
    restart: on-failure
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=gogs'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    volumes:
      - './psql:/var/lib/postgresql/data'
    network_mode: host
    # ports:
    #   - '5432:5432'
  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    restart: always
    environment:
        - 'RUN_CROND=true'
    volumes:
        - './gogs:/data/gogs'
        - './repo:/data/git/gogs-repositories'
    network_mode: host
    # ports:
    #     - '3022:22'
    #     - '3000:3000'
  athens:
    image: gomods/athens:latest
    container_name: athens
    restart: always
    environment:
      - 'ATHENS_DISK_STORAGE_ROOT=/var/lib/athens'
      - 'ATHENS_STORAGE_TYPE=disk'
    volumes:
        - './proxy:/var/lib/athens'
    ports:
      - '3001:3000'
  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
        - './registry:/var/lib/registry'
    ports:
      - '5000:5000'
volumes:
    gogs-data:
        driver: local
